# .github/workflows/daily-issue.yml

name: Daily Baekjoon Issue

on:
  schedule:
    - cron: '0 15 * * *'  # ✅ 매일 한국시간 자정 실행
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run script
      env:
        IMPLEMENTATION_GH_TOKEN: ${{ secrets.GH_TOKEN }}  # ✅ GH_TOKEN(secret) → IMPLEMENTATION_GH_TOKEN(env)로 매핑
      run: python daily_issue.py
