name: Daily Baekjoon Issue

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run script
      env:
        GH_TOKEN: ${{ secrets.IMPLEMENTATION_GH_TOKENS }}
      run: python daily_issue.py
